### ISSUE TITLE
[BUG] Transfer from Android to iOS

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#11]
**Describe the solution you'd like**
Transfer my data and entities from Android phone entity to new iPhone entity and application

**Task List**
- [ ] Update sleep trigger automation (Awaiting #29 Patch)
- [ ] Update Node-Red Automations with new notify entity (Awaiting #29 Patch)
- [ ] [Update BLE for both mine and wifes phone with ESPresense](https://espresense.com/beacons/apple)
- [x] Set-Up HA Companion fully (sensors, BLE)
- [x] Transfer notification entity to iOS entity
- [x] Update device tracker to iOS & look at Life360 Alternative https://github.com/smcnab1/op-question-mark/issues/12
- [x] Update dashboard person pop up with new entities
- [x] Update alarm notifications to iOS format including Frigate trigger
- [x] Update TTS popup 
- [x] Add Car Wash App to open on notification

**Comment by smcnab1** [comment]
Set-Up BLE for iPhone - https://espresense.com/beacons/apple
