### ISSUE TITLE
Add Guest Login System

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#117]
Implement easy access login system for guests to login to HA instance

[Web Server](https://nathanorick.com/ha-automatic-guest-login/)

**Tasks**

- [x] Implement [System](https://nathanorick.com/ha-automatic-guest-login/) on spare RPI 
- [x] Test login procedure to make sure easy to use and works as expected.
- [x] Ensure server runs constantly, even on re-boot

**Comment by smcnab1** [comment]
Added using [cnorick's ha-auto-guest-login feature](https://github.com/cnorick/ha-auto-guest-login). Enabled to work on startup of spare RPI and if restarts, will kick in again so always running. Since recording screen below, have changed wording of splash screen prior to HA redirect.



https://user-images.githubusercontent.com/108990188/189782092-9997a5eb-1769-46be-9e87-a9c36561a969.mov
