### ISSUE TITLE
Home Page for Guest Dashboard

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#118]
**Tasks**

- [x] Weather
- [x] How far Sam & Leah are from home
- [x] Navigation to rooms & other pages with what each page features.
- [x] Add short instructions
  - [x] Important notices/information
  - [x] How to use dashboard
  - [x] What to expect from automations
