### ISSUE TITLE
Hall Page for Guest Dashboard

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#122]
**Tasks**

- [ ] Temperature
- [ ] Tablet Dashboard Usage
- [ ] Instructions for using things
- [ ] Instructions for where things are
- [ ] Highlight how automations will work and lights work
- [ ] Manual Toggling options
  - [ ] Lighting
