### ISSUE TITLE
Media Page for Guest Dashboard

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#123]
**Tasks**

- [ ] Instructions for using things
- [ ] Instructions for where things are
- [ ] Highlight how automations will work
- [ ] Usage of media players
  - [ ] Living Room TV
  - [ ] Living Room Sonos
  - [ ] Living Room Google Home
