### ISSUE TITLE
Lighting Page for Guest Dashboard

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#124]
**Tasks**

- [ ] Instructions for using things
- [ ] Instructions for where things are
- [ ] Highlight how automations will work and lights work
- [ ] Manual Toggling options for ALL Lights
