### ISSUE TITLE
Instruction Page for Guest Dashboard

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#125]
**Tasks**

- [ ] General instructions for how to use things
- [ ] General instructions for where things are
- [ ] Use of dashboard instructions
- [ ] Use of lighting
- [ ] Use of media
