### ISSUE TITLE
Implement Guest Mode Toggle

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#127]
**Tasks**

- [ ] Create input boolean
- [ ] Add input boolean switch to normal dashboard
- [ ] Disable living room camera recording trigger if guest mode on (Frigate)
- [ ] Add input boolean to automations as conditions
  - [ ] Living Room Lighting (Node-RED)
  - [ ] Alarm reminder notifications
  - [ ] TTS functions
  - [ ] Mac Get off Computer automation
