### ISSUE TITLE
Update Documentation for Guest Dashboard

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#129]
**Tasks**

- [ ] Add area on README.md for full implementation guidelines
- [ ] Add extra automations to page
- [ ] Add extra input_boolean to README.md
- [ ] Look at adding feature README for full documentation.
- [ ] Update Node-RED automations with input boolean to stop automations.

**Comment by smcnab1** [comment]
**Entities to Add**

- [ ] sensor.bring_with_you (home page)
