### ISSUE TITLE
Name Input Page for Guest Dashboard

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#130]
**Tasks**

- [x] Create Input Text Entity for name input
- [x] Add Input ability and description to initial page
- [x] Create button that when enters, redirects to home page with personalised name and instructions.
