### ISSUE TITLE
TTS - Welcome Home

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#3]
**Describe the solution you'd like**
Simple welcome home message on Hall Tablet with changes in entities whilst gone and other helpful info.

**Task List**
- [ ] Create basic macro template
- [ ] Create simple automation to recognise wife coming home
- [ ] Create simple automation to recognise me coming home
- [ ] Create simple automation to recognise both coming home
- [ ] Create push automation with template to hall tablet TTS
- [ ] Create welcome home entity automation customised for me or wife (music/lighting)
