### ISSUE TITLE
[BUG] Add Minimalist Pop-Up Light & Media Cards

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#32]
Add minimalist pop-up light & media card to every light card for better control

- [x] Add box shadow to polio slider cards to make readability easier

**Specific Fixes (Phone)**
***Home Page***
- [x] Phone Weather Popup, fix button press it's for back and radar
- [x] Fix people card map pop ups to actually show location
- [x] Room card pop ups

***Hall***
- [x] Lights
- [x] Fix Scene Automations #30

***Living Room***
- [x] Lights
- [x] Fix Scene Automations #30
- [x] Media

***Bedroom***
- [x] Lights
- [x] Fix Scene Automations #30
- [x] Media

***Office***
- [x] Lights
- [x] Fix Scene Automations #30
- [x] Media

***Kitchen***
- [x] Lights
- [x] Fix Scene Automations #30
- [x] Media

**Specific Fixes (Tablet)**
***Home Page***
- [x] Phone Weather Popup, fix button press it's for back and radar
- [x] Fix people card map pop ups to actually show location
- [x] Room card pop ups
- [x] Right side pop ups

***Hall***
- [x] Lights
- [x] Fix Scene Automations #30

***Living Room***
- [x] Lights
- [x] Fix Scene Automations #30
- [x] Media

***Bedroom***
- [x] Lights
- [x] Fix Scene Automations #30
- [x] Media

***Office***
- [x] Lights
- [x] Fix Scene Automations #30
- [x] Media

***Kitchen***
- [x] Lights
- [x] Fix Scene Automations #30
- [x] Media

**Comment by smcnab1** [comment]
Awaiting new update on [UI Lovelace Minimalist](https://github.com/UI-Lovelace-Minimalist/UI) to fix with Browser-Mod Update
