### ISSUE TITLE
[BUG] Re-Format Automations to make work

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#38]
**Describe the bug**
Automations can be flakey with duplicated entitiy IDs for automations.

**Task**
- [x] Re-Format Automations
- [x] Remove UI created Automations
- [x] Test and Commit
