### ISSUE TITLE
TTS - Morning Briefing (Me)

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#5]
**Describe the solution you'd like**
Morning Briefing like wife's but BETTER including news, tv automation for short time frame and desk lights & PC on.

**Task List**
- [ ] Create macro template
- [ ] Create trigger method ? Sleep sensor off if I'm home
- [ ] Create automation to push
- [ ] Create automation for other functions
