### ISSUE TITLE
[FR] Meeting Notification for Wife

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#6]
**Describe the solution you'd like**
Simple notification for wife when arrives home if I am on a meeting

**Describe alternatives you've considered**
Already have light change behind desk for wife to know.

**Task List**
- [ ] Duplicate trigger for light change to trigger input boolean
- [ ] Create trigger for arriving home
- [ ] Create push notification to wife's phone
- [ ] Gain wife approval
