### ISSUE TITLE
Implement WLED 

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/op-question-mark#8]
**Describe the solution you'd like**
Simple WLED setup across house to replace old LED strips with poor connections

**Describe alternatives you've considered**
Govee addressable LEDs. Pre-Set kits of WLED. All expensive and not fully customisable

**Task List**
- [ ] Measure LED requirements 
- [ ] Work out power usage
- [ ] Purchase supplies needed
- [ ] Build test setup
- [ ] Replace Hall LEDs
- [ ] Replace Living Room LEDs
- [ ] Replace Kitchen LEDs
- [ ] Replace Bedroom LEDs
- [ ] Implement into automations

**Measurements & Power**
_Hall_ (Length) (Power)
_Living Room_ (Length) (Power)
_Kitchen_ (Length) (Power)
_Bedroom_ (Length) (Power)
**Total** (Length) (Power)

**Comment by smcnab1** [comment]
[Link to YouTube Set-Up](https://youtu.be/j15pjU3YZfg)

**Comment by smcnab1** [comment]
https://m.facebook.com/groups/HomeAssistant/permalink/3331594567111890/
